label: Settings
icon: cog
columns:
  - width: 2/3
    fields:
      ## Cookie Banner
      cookie-headline:
        type: headline
        label: Cookie Banner
      cookie_banner_text:
        label: Banner Text
        buttons: false
        size: small
        type: textarea
      cookie_banner_accept:
        label: Accept Banner
        type: text
      cookie_banner_reject:
        label: Reject Banner
        type: text

      tracking_banner_header:
        type: headline
        label: Tracking
      analytics:
        translate: false
        type: text
        icon: code
        label: Google Analytics
      maps:
        translate: false
        type: text
        icon: code
        label: Google Maps Key API
      hotjar:
        translate: false
        type: text
        icon: code
        label: Hotjar ID
      log_rocket:
        translate: false
        type: text
        icon: code
        label: Log Rocket
  - width: 1/3
    fields:
      nav_phone:
        label: Navigation Phone
        type: text
      JANITOR_CACHE:
        type: janitor
        label: Clean Cache
        progress: Cleaning Cache...
        job: cleanCache
      JANITOR_FLUSH_PAGES:
        type: janitor
        label: Flush Pages
        progress: Flushing Kirby...
        job: flushPages
      JANITOR_FLUSH_SESSION:
        type: janitor
        label: Flush Sessions
        progress: Flushing Sessions...
        job: flushSessions
