label: Settings
icon: cog
columns:
  - width: 1/3
    fields:
      nav_phone:
        label: Navigation Phone
        type: text
      ## Cookie Banner
      HEADLINE_COOKIE_BANNER:
        label: Cookie banner
        numbered: false
        type: headline
        numbered: false
      cookie_banner_text:
        label: Banner Text
        buttons: false
        size: small
        type: textarea
      cookie_banner_accept:
        label: Accept Banner
        type: text
      cookie_banner_reject:
        label: Reject Banner
        type: text
  - width: 1/3
    fields:
      HEADLINE_TRACKING:
        type: headline
        label: Tracking
        numbered: false
      google_tag_manager:
        translate: false
        type: text
        icon: chart
        label: Google Tag Manager
      analytics:
        translate: false
        type: text
        icon: chart
        label: Google Analytics
      maps:
        translate: false
        type: text
        icon: map
        label: Google Maps Key API
      hotjar:
        translate: false
        type: text
        icon: code
        label: Hotjar ID
      log_rocket:
        translate: false
        type: text
        icon: bug
        label: Log Rocket
  - width: 1/3
    fields:
      JANITOR_CACHE:
        type: janitor
        label: Clean Cache
        progress: Cleaning Cache...
        job: cleanCache
      JANITOR_FLUSH_PAGES:
        type: janitor
        label: Flush Pages
        progress: Flushing Kirby...
        job: flushPages
      JANITOR_FLUSH_SESSION:
        type: janitor
        label: Flush Sessions
        progress: Flushing Sessions...
        job: flushSessions
